# Generated by Django 5.1 on 2024-09-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_app',
            field=models.CharField(default=1234567890123456, max_length=16),
            preserve_default=False,
        ),
    ]
