# Generated by Django 5.1 on 2024-10-02 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizadorEmail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_markers', to='organizadorEmail.markers')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_markers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
